#base image


#workdir

#copy

#run

#port

#command

FROM python:3.10-slim

WORKDIR /app

# Copy requirements from PROJECT ROOT
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy frontend code
COPY frontend/ ./frontend/

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]